theme: jekyll-theme-minimal


title:          ПРОСТРАНСТВО СМЫСЛОВ
email:          babilonmediagroup@gmail.com
description:    "Медиа-проект Дмитрия Запольского"
subtitle:       "Медиа-проект Дмитрия Запольского"
url:            http://zapsm.github.io
lang:           ru-RU
author:         ПРОСТРАНСТВО СМЫСЛОВ
copyright:      "&#x2117; &amp; &#xA9; 2015"
